spring:
  datasource:
    url: jdbc:mysql://${mysql.url:localhost}:3306/yamada
    hikari:
      username: ${mysql.username:root}
      password: ${mysql.password:123456}
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.addr:127.0.0.1:8848}
      config:
        server-addr: ${nacos.addr:127.0.0.1:8848}
        namespace: ee548335-68fe-4312-8e06-996beff99138
  redis:
    database: ${redis.database:0}
    host: ${redis.host:localhost}
    port: 6379
    password: ${redis.password:123456}
management:
  endpoints:
    web:
      exposure:
        # 暴露所有端点
        include: "*"