spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yamada
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:111.230.220.64:8848}
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 111
management:
  endpoints:
    web:
      exposure:
        # 暴露所有端点
        include: "*"