server:
  port: 8040
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true