spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:111.230.220.64:8848}
management:
  endpoints:
    web:
      exposure:
        # 暴露所有端点
        include: "*"
  endpoint:
    health:
      show-details: always